# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  www.teknovagrant.com:
    site_hosts:
      - canonical: www.teknovagrant.com
      - canonical: teknovagrant.com
    redirects:
      - teknovagrant.com
    user: deploy
    group: www-data
    local_path: ../tekno # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:hitek/tekno.git # replace with your Git repo URL
    repo_subtree_path: tekno # relative path to your Bedrock/WP directory in your repo
    branch: master
    env:
      wp_home: http://www.teknovagrant.com
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
      duration: 120s
      skip_cache_uri: /wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml
      skip_cache_cookie: comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in
